# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'SSZipArchive', '~> 2.1.4'

target 'ScratchJr Free' do
end

target 'ScratchJrTests' do

end
