# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'Google/Analytics', '~> 1.0.0'

target 'ScratchJr Free' do
    
end

target 'ScratchJrTests' do
end

